### PR TITLE
Fix flush() and artisan commands

### PR DESCRIPTION
**Pull request by anaxamaxan**
We were getting two issues with this package. First, event listeners calling Cache::keywords()->flush() would emit this error:
~~~
[ErrorException]                                                                                                                          
  call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\RedisStore' does not have a method 'keywords'
~~~
We found that removing line 120 in config/app.php:
~~~
    Illuminate\Cache\CacheServiceProvider::class,
~~~
would fix that. But then artisan would fail on cache:clear, because the console commands were not being registered in the package, giving this error:
~~~
  [InvalidArgumentException]                               
  There are no commands defined in the "cache" namespace. 
~~~

So I made a couple small changes to the service provider make that happen.

### CODE REVIEW

**Comment by anaxamaxan** [comment]
Oh, I didn't add any new tests, because the relevant method is part of the framework.

**Comment by Propaganistas** [comment]
Thanks for your report.

After some more digging, it seems that the core class override simply does not occur in some parts of the Laravel Application (e.g. artisan or event listeners)...

Since this is rather a generic problem and not solely related to this package, completely removing `CacheServiceProvider` is **not** a viable solution.

I don't have a clue how to solve this at the moment, but let's ask the community:

https://github.com/laravel/framework/issues/10439
http://stackoverflow.com/questions/32880068/overridden-core-class-does-not-work-when-in-artisan
http://laravel.io/forum/10-01-2015-overridden-core-class-does-not-work-when-in-artisan

**Comment by anaxamaxan** [comment]
Cool, makes sense. I'd suggest posting the question on Laracasts forum too. Seems like the most active forum these days. For now, we made a workaround via a service provider. We greatly appreciate this library!

**Comment by Propaganistas** [comment]
Hi @anaxamaxan 

I managed to track down the issue. I've written a full notice on top of the Service Provider file.
Below's a copy for sake completeness of this PR.

```
/**
 * This Service Provider extends Laravel's built-in CacheServiceProvider class on a very specific purpose.
 * In fact we're actually overriding ALL bindings registered in CacheServiceProvider to be handled
 * through this class (although most of them are transparently passed to CacheServiceProvider).
 * Why? Because Artisan loads all deferred providers at once using a key-sorted providers array:
 *
 *  ...
 *  "cache" => CacheKeywordsServiceProvider,
 *  "cache.store" => CacheServiceProvider,
 *  ...
 *
 * As you can see, the cache.store binding calls the built-in CacheServiceProvider afterwards and hence renders
 * our binding useless if we would only bind our override. So we are obliged to convert the providers array to:
 *
 * ...
 *  "cache" => CacheKeywordsServiceProvider,
 *  "cache.store" => CacheKeywordsServiceProvider,
 *  ...
 *
 * in order to have our override resolve correctly.
 *
 * It's sort of a hack, but it's the only way to make it work across the entire Application.
 */
```

**Pull request closed without merging**
